name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - uses: HatsuneMiku3939/direnv-action@v1
    - name: direnv allow
      run: direnv allow .
    - name: go mod tidy
      run: direnv exec . go mod tidy
    - name: exit if not tidy
      run: |
        git diff --exit-code go.mod
        git diff --exit-code go.sum
    - run: ./scripts/build_wasm.sh
    - uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - run: npx pkg-pr-new publish 
      working-directory: examples/wasm
